import {rooms,walls,ideaFor,colors,electrical,plumbing,network} from './data.js';
import {allElectrical} from './room-electrical.js';
import {documentContent} from './review.js';
import {defaultProject as electricalProject,ensureDesign,calculate as calculateElectrical,allRooms as electricalRooms,worldPoint as electricalWorldPoint,byType as electricalTypes} from './studio-data.js';
import {drawing as liveDrawing,topology as liveTopology,table as liveTable,pointRows,pointHeaders,controlRows,controlHeaders,esc as escapeElectrical} from './electrical-report.js';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const titles=['Interior top view','Whole-house 3D','Exterior','Electrical','Plumbing','Network','Before plaster','Photo & interior concepts','Compound & gate'];
const sheets=['A-01 · ARCHITECTURE','A-02 · SPATIAL MODEL','A-03 · EXTERIOR STUDY','E-01 · ELECTRICAL CONCEPT','P-01 · PLUMBING CONCEPT','N-01 · DATA & SECURITY','R-01 · SITE RELEASE','I-01 · PHOTO REFERENCE','S-01 · SITE STUDY'];
let state={view:1,floor:0,scheme:'proposed',scope:'all',explode:true,roof:true,furniture:true,wallHeight:1,heights:[3.0,3.0],units:'m',dimensions:false,source:true,selected:null,sub:'plan',electricalFilter:'all',compound:true,gateWidth:3.6,gateSide:'left',gateOpen:false},model=null,loadVersion=0;
let viewBox=[-25,-20,799,1090],pointerStart=null,dragged=false;
$('#views').innerHTML='<a class="studioLink" href="studio.html">Design & electrical editor ↗</a>'+titles.map((n,i)=>`<button data-view="${i}">${n}</button>`).join('');$('#dimensions').checked=false;
$('.floorbuttons').insertAdjacentHTML('beforebegin','<div class="schemebuttons"><button data-scheme="existing">Existing*</button><button data-scheme="proposed">Proposed</button></div><small class="footnote" style="margin:7px 0 17px">*Plan-based reconstruction; current photographs reviewed.</small>');
$('.controls .footnote:last-child').textContent='Areas quoted from the discussion plan. Room units confirmed by owner. Outline and heights remain approximate.';
function fmt(m){if(state.units==='m')return `${m.toFixed(2)} m`;const n=Math.round(m/.0254);return `${Math.floor(n/12)}′ ${n%12}″`;}const dimensions=r=>r.dim.map(fmt).join(' × ');
function activeRooms(){return rooms[state.floor].filter(r=>state.scheme==='proposed'||!r.extension)}
function controls(){
 $$('[data-floor]').forEach(b=>b.classList.toggle('active',+b.dataset.floor===state.floor));$$('[data-scheme]').forEach(b=>b.classList.toggle('active',b.dataset.scheme===state.scheme));$$('[data-view]').forEach(b=>b.classList.toggle('active',+b.dataset.view===state.view));
 $('#roomlist').innerHTML=activeRooms().map(r=>`<button class="roomitem ${state.selected===r.id?'selected':''}" data-room="${r.id}">${r.name}${r.extension?' +':''}<small>${dimensions(r)}</small></button>`).join('');
 const is3D=[1,2].includes(state.view);$('#extraControls').innerHTML=is3D?`<label>Show <select id="scope"><option value="all" ${state.scope==='all'?'selected':''}>Entire house</option><option value="floor" ${state.scope==='floor'?'selected':''}>Selected floor</option></select></label><button id="topDown">Top-down view</button><label class="check"><input id="furniture" type="checkbox" ${state.furniture?'checked':''}>Furniture</label>${state.view===1?`<label class="check"><input id="explode" type="checkbox" ${state.explode?'checked':''}>Separate floors</label><label class="heightlabel">Cutaway wall height <input id="wallHeight" type="number" min="0.2" max="2.9" step="0.1" value="${state.wallHeight}"> m</label>`:`<label class="check"><input id="roof" type="checkbox" ${state.roof?'checked':''}>Roof study</label><button id="front">Front view</button>`}<p class="eyebrow" style="margin-top:20px">MODEL HEIGHTS</p>${state.heights.map((h,i)=>`<label class="heightlabel">${i?'First floor to roof':'Ground to first floor'}<br><input data-height="${i}" type="number" min="2.5" max="4.5" step="0.05" value="${h}"> m</label>`).join('')}<small class="footnote" style="margin-top:8px">Owner reports 3.00 m. Interpreted floor-to-floor; confirm clear height and slab thickness.</small>`:'';
 $('#source').closest('label').hidden=is3D||state.view>=6;$('#dimensions').closest('label').hidden=state.view>=6;$('#units').closest('label').hidden=state.view>=6;
 if([2,8].includes(state.view))$('#extraControls').insertAdjacentHTML('beforeend',`<div class="sitecontrols"><p class="eyebrow">COMPOUND PROPOSAL</p><label class="check"><input id="compound" type="checkbox" ${state.compound?'checked':''}>Show 2 m compound wall</label><label>Clear gate width <input id="gateWidth" type="number" min="2.5" max="4.8" step="0.1" value="${state.gateWidth}"> m</label><label>Gate location <select id="gateSide"><option value="left" ${state.gateSide==='left'?'selected':''}>Left; slides right</option><option value="right" ${state.gateSide==='right'?'selected':''}>Right; slides left</option></select></label><label class="check"><input id="gateOpen" type="checkbox" ${state.gateOpen?'checked':''}>Open gate in 3D</label><small class="footnote">1 m each side · front wall 5 m from sitout · gate side/width proposed · rear unknown</small></div>`);
 if(state.view===3)$('#extraControls').innerHTML=`<label>Points <select id="electricalFilter"><option value="all">All point groups</option><option value="power">AC / power / data</option><option value="lighting">Lights / switches</option><option value="service">Service / future</option></select></label><button id="allRooms">All rooms</button><small class="footnote">Select a room for its proposed point positions. Heights and offsets are proposals.</small>`;if($('#electricalFilter')){$('#electricalFilter').value=state.electricalFilter;$('#electricalFilter').onchange=e=>{state.electricalFilter=e.target.value;if(state.sub==='plan')drawPlan();else $('#documentView').innerHTML=documentContent(state,points);e.stopPropagation()};$('#allRooms').onclick=()=>{state.selected=null;viewBox=[-25,-20,799,1090];if(state.sub==='plan')drawPlan();else $('#documentView').innerHTML=documentContent(state,points);controls();$('#details').innerHTML=intro()}}
 $('#extraControls').onchange=e=>{const t=e.target;if(t.dataset.height!==undefined){const v=+t.value;if(!Number.isFinite(v)||v<2.5||v>4.5){t.value=state.heights[+t.dataset.height];return}state.heights[+t.dataset.height]=v}else if(t.id==='wallHeight'){const v=+t.value;if(!Number.isFinite(v)||v<.2||v>2.9){t.value=state.wallHeight;return}state.wallHeight=v}else if(t.id==='gateWidth'){const v=+t.value;if(v<2.5||v>4.8||!Number.isFinite(v)){t.value=state.gateWidth;return}state.gateWidth=v}else if(['scope','gateSide'].includes(t.id))state[t.id]=t.value;else state[t.id]=t.checked;if([1,2].includes(state.view))show3D(false);else render(false)};if($('#front'))$('#front').onclick=()=>model?.front();if($('#topDown'))$('#topDown').onclick=()=>model?.top();
}
function intro(){const p=state.scheme==='proposed';return `<span class="tag ${p?'':'warn'}">${p?'Proposed · review only':'Existing · plan-based'}</span><h2>${p?'A lighter, more adaptable home.':'The existing arrangement.'}</h2><p>${p?'Rearranged seating, fitted storage, a plaster media screen and coordinated materials. The two pink upstairs enclosures are new.':'Reconstructed from the concept plan and supplied photographs, without the two new upstairs enclosures. Loose furniture is omitted to reflect the supplied empty-room photos; unseen areas remain plan-based.'}</p><div class="fact"><span>Ground floor</span><b>1,205 sq ft</b></div><div class="fact"><span>First floor</span><b>867 sq ft</b></div><div class="fact"><span>Plan total*</span><b>2,072 sq ft</b></div><p style="font-size:12px;margin-top:7px">*The plan does not clarify whether these areas include the additions; no existing-area total is inferred.</p><hr><h3>Established</h3><p>Room labels transcribed from the PDF. Units and the two unbuilt pink additions confirmed by the owner.</p><h3>Approximate</h3><p>Wall coordinates are traced. Photos inform porch columns, projecting concrete bands, window character and the living/dining frame. Exact openings, thicknesses and stair geometry still need measurement. Owner reports 3.00 m per floor, interpreted floor-to-floor.</p><p><a href="https://www.google.com/maps?q=8.8149833,76.9398606&z=17&hl=en" target="_blank" rel="noreferrer">Kummil / Street View</a> — image inspected: April 2023, not a current condition record.</p>`;}
function selectRoom(id){if([3,5].includes(state.view)){state.selected=id;const rr=rooms.flat().find(r=>r.id===id);if(rr)state.floor=rooms[0].includes(rr)?0:1;render(false);return;}const r=rooms.flat().find(r=>r.id===id);if(!r)return;state.selected=id;state.floor=rooms[0].includes(r)?0:1;controls();const i=ideaFor(r);$('#details').innerHTML=`<span class="tag ${r.extension?'warn':''}">${r.extension?'New addition · not yet built':'Dimension from plan'}</span><h2>${r.name}</h2><div class="measure">${dimensions(r)}</div><p>PDF label: ${r.dim.map(v=>Math.round(v*100)).join(' × ')}</p><hr><h3>${i.title}</h3><p>${i.text}</p><p>${i.detail}</p><h3>Before closing the wall</h3><p>${i.services}</p>${[1,2].includes(state.view)?'<button id="focusRoom">Focus on this room</button>':''}`;$$('[data-room]').forEach(b=>b.classList.toggle('selected',b.dataset.room===id));if($('#focusRoom'))$('#focusRoom').onclick=async()=>{state.scope='floor';controls();await show3D(false);model?.focusRoom(r,state.floor)};if(state.view===3){viewBox=[r.rect[0]-120,r.rect[1]-90,r.rect[2]+240,r.rect[3]+180]}if([0,3,4,5].includes(state.view)){if(state.sub==='plan')drawPlan();else $('#documentView').innerHTML=documentContent(state,points);}}
function points(){return (state.view===3?allElectrical(state.floor):(state.view===4?plumbing:network)[state.floor]).filter(p=>state.view!==3||(!state.selected||p.roomId===state.selected||p.type==='DB')&&(state.electricalFilter==='all'||p.group===state.electricalFilter||p.type==='DB')).filter(p=>state.scheme==='proposed'||!(state.floor===1&&['L-F5','L-F6','S-F4','WH-F1','P-F1','P-F2'].includes(p.id)));}
function pointDetails(id){const p=points().find(p=>p.id===id);if(p)$('#details').innerHTML=`<span class="tag warn">Proposed point · position unverified</span><h2>${p.name}</h2><div class="measure">${p.id}</div><p>${p.note}</p>${p.offset?`<div class="fact"><span>Across room / from rear</span><b>${p.offset.map(v=>v.toFixed(2)+' m').join(' / ')}</b></div><div class="fact"><span>Proposed height AFF</span><b>${typeof p.aff==='number'?p.aff.toFixed(2)+' m':p.aff}</b></div><p>${p.reference}</p>`:''}<hr><p>Position is indicative. Final offsets, mounting heights, sizes, clearances and routes require measured setting-out and professional design.</p><p>No cable size, breaker rating, pipe diameter or drain fall is approved by this viewer.</p>`;}
const route=(p,c,d='8 6')=>`<polyline points="${p.map(a=>a.join(',')).join(' ')}" fill="none" stroke="${c}" stroke-width="3" stroke-dasharray="${d}" opacity=".8"/>`;
function routes(ps){let h='';if(state.view===3||state.view===5){const s=ps.find(p=>p.type==='DB')||ps[0],c=state.view===3?colors.electric:colors.network;for(const p of ps.filter(p=>p!==s)){const x=state.view===3?365:350;h+=route([[s.x,s.y],[x,s.y],[x,p.y],[p.x,p.y]],p.type==='R'?colors.future:c)}}else{const off=state.floor?20:0;for(const p of ps.filter(p=>p.type==='CW')){const x=p.y<460?21+off:706+off;h+=route([[x,86],[x,p.y-10],[p.x,p.y-10]],colors.cold);if(!p.name.includes('Common'))h+=route([[x+9,86],[x+9,p.y+5],[p.x,p.y+5]],colors.hot);h+=route([[p.x,p.y+20],[x-8,p.y+20],[x-8,1012]],colors.waste,'')}h+=route([[715+off,100],[715+off,1012]],colors.future)}return h;}
function drawPlan(){let h='';const source=state.source,rs=activeRooms();if(source)h+=`<image href="assets/${state.floor?'first':'ground'}.png" width="${state.floor?749:724}" height="1046" opacity="${state.view===0?1:.42}"/>`;else{h+='<rect x="30" y="25" width="690" height="985" fill="#f3f4f0"/>';for(const r of rs)h+=`<rect x="${r.rect[0]}" y="${r.rect[1]}" width="${r.rect[2]}" height="${r.rect[3]}" fill="${r.kind==='wet'?'#d8e9e8':r.kind==='bed'?'#eee4d4':'#fafbf8'}"/>`;for(const w of walls[state.floor])if(!w[4]||state.scheme==='proposed')h+=`<line x1="${w[0]}" y1="${w[1]}" x2="${w[2]}" y2="${w[3]}" stroke="#324e57" stroke-width="9"/>`;}
 if(state.floor===1&&state.scheme==='existing')h+='<rect x="32" y="198" width="321" height="147" fill="#eef0eb"/><text x="190" y="270" font-size="15" fill="#536e6d" text-anchor="middle">Bathroom addition not built</text><rect x="375" y="288" width="196" height="179" fill="#eef0eb"/><text x="472" y="385" font-size="14" fill="#536e6d" text-anchor="middle">Laundry not built</text>';
 for(const r of rs){const [x,y,w,d]=r.rect,s=state.selected===r.id;h+=`<g data-room="${r.id}" tabindex="0" role="button" aria-label="${r.name}, ${dimensions(r)}"><rect x="${x}" y="${y}" width="${w}" height="${d}" fill="${s?'#0b9b8255':'#ffffff01'}" stroke="${s?'#087f74':r.extension?'#cc36c9':'none'}" stroke-width="4"/>${(!source||state.dimensions)?`<rect x="${x+w/2-92}" y="${y+d/2-25}" width="184" height="49" rx="4" fill="#fffffff0"/><text x="${x+w/2}" y="${y+d/2-4}" text-anchor="middle" font-size="15" fill="#163a47">${r.name}</text><text x="${x+w/2}" y="${y+d/2+15}" text-anchor="middle" font-size="14" fill="#14776c">${dimensions(r)}</text>`:''}</g>`;}
 if([3,4,5].includes(state.view)){const ps=points();h+=routes(ps);for(const p of ps){const c=state.view===3?colors.electric:state.view===5?colors.network:p.type==='ST'?colors.waste:p.type==='RW'?colors.future:colors.cold;h+=`<g data-point="${p.id}" tabindex="0" role="button" aria-label="${p.id}: ${p.name}"><circle cx="${p.x}" cy="${p.y}" r="17" fill="white" stroke="${c}" stroke-width="3"/><text x="${p.x}" y="${p.y+5}" text-anchor="middle" font-size="12" font-weight="700" fill="${c}">${p.type}</text><text x="${p.x+21}" y="${p.y+5}" font-size="11" fill="${c}" stroke="white" stroke-width="3" paint-order="stroke">${p.id}</text></g>`;}}
 $('#plan').innerHTML=h;$('#plan').setAttribute('viewBox',viewBox.join(' '));
}
function legend(){const a=state.view===3?[[colors.electric,'Electrical route corridor'],[colors.future,'Future provision']]:state.view===4?[[colors.cold,'Cold'],[colors.hot,'Hot'],[colors.waste,'Soil / waste'],[colors.future,'Rainwater']]:state.view===5?[[colors.network,'Data home runs'],[colors.future,'Spare route']]:[['#497b70','Retained layout'],[colors.extension,'Proposed addition']];$('#legend').innerHTML=a.map(([c,t])=>`<span><i class="swatch" style="background:${c}"></i>${t}</span>`).join('');}
async function show3D(reset=true){const v=++loadVersion;try{if(!model){model=await import('./model3d.js');model.init($('#threeWrap'),selectRoom)}if(v!==loadVersion)return;model.rebuild({...state,view:state.view===2?'exterior':'cutaway'});showSavedFixtures();if(reset)model.reset();if(!$('#threeWrap .viewtools'))$('#threeWrap').insertAdjacentHTML('beforeend','<div class="viewtools">Drag to orbit · right-drag to pan · scroll / pinch to zoom · arrows to pan</div>');}catch(e){$('#threeWrap').innerHTML='<p class="error">The 3D view could not start. Enable WebGL in your browser or use the top view while the graphics issue is resolved.</p>';console.error(e)}}
function render(reset=true){controls();if([3,5].includes(state.view)){renderLiveElectrical();return;}$('#viewtitle').textContent=titles[state.view];$('#sheet').textContent=sheets[state.view]+(state.view<=5?` · ${state.scheme.toUpperCase()}`:'');const three=[1,2].includes(state.view),doc=state.view>=6||([3,4,5].includes(state.view)&&state.sub!=='plan');$('#threeWrap').hidden=!three;$('#planWrap').hidden=three||doc;$('#documentView').hidden=!doc;$('.workspace').classList.toggle('documentmode',doc);$('#routeTabs')?.remove();if([3,4,5].includes(state.view))$('.drawinghead').insertAdjacentHTML('afterend',`<div class="subnav" id="routeTabs">${[['plan','Floor route sketch'],['diagram','System diagram'],['register','Point register']].map(([id,t])=>`<button data-sub="${id}" class="${state.sub===id?'active':''}">${t}</button>`).join('')}</div>`);if(three)show3D(reset);else if(doc)$('#documentView').innerHTML=documentContent(state,points);else drawPlan();legend();$('#legend').hidden=doc;$('#hint').textContent=three?'Approximate geometry · room labels from plan · 3.00 m owner-reported height; floor-to-floor interpretation':doc?'Review draft · not a construction release':[3,4,5].includes(state.view)?'Routes are corridor proposals, not individual wire/pipe setting-out. Click any point.':'Original plan underlay: furniture shown is from the PDF. Use Whole-house 3D → Top-down for the proposed furniture layout.';if(state.selected&&activeRooms().some(r=>r.id===state.selected))selectRoom(state.selected);else $('#details').innerHTML=intro();}
document.addEventListener('click',e=>{const t=e.target.closest('button,[data-room],[data-point]');if(!t||dragged)return;if(t.dataset.view!==undefined){state.view=+t.dataset.view;state.sub='plan';state.selected=null;if(state.view===2){state.scope='all';state.explode=false}render()}else if(t.dataset.floor!==undefined){state.floor=+t.dataset.floor;state.selected=null;if(state.view===1)state.scope='floor';viewBox=[-25,-20,799,1090];render()}else if(t.dataset.scheme){state.scheme=t.dataset.scheme;state.selected=null;render(false)}else if(t.dataset.room)selectRoom(t.dataset.room);else if(t.dataset.point)pointDetails(t.dataset.point);else if(t.dataset.sub){state.sub=t.dataset.sub;render(false)}});
document.addEventListener('keydown',e=>{if(['Enter',' '].includes(e.key)&&(e.target.dataset.room||e.target.dataset.point)){e.preventDefault();e.target.dataset.room?selectRoom(e.target.dataset.room):pointDetails(e.target.dataset.point)}});
document.addEventListener('change',e=>{if(e.target.dataset.check!==undefined){const ids=$$('[data-check]:checked').map(t=>+t.dataset.check);try{localStorage.setItem('house-review-checks',JSON.stringify(ids))}catch{}e.target.closest('.checkrow').classList.toggle('done',e.target.checked)}});
$('#units').onchange=e=>{state.units=e.target.value;render(false)};$('#dimensions').onchange=e=>{state.dimensions=e.target.checked;render(false)};$('#source').onchange=e=>{state.source=e.target.checked;drawPlan()};$('#print').onclick=()=>window.print();$('#reset').onclick=()=>{viewBox=[-25,-20,799,1090];[1,2].includes(state.view)?model?.reset():drawPlan()};
const svg=$('#plan');svg.addEventListener('wheel',e=>{e.preventDefault();const nw=Math.max(180,Math.min(1600,viewBox[2]*(e.deltaY>0?1.12:.89))),q=nw/viewBox[2];viewBox=[viewBox[0]+(viewBox[2]-nw)/2,viewBox[1]+viewBox[3]*(1-q)/2,nw,viewBox[3]*q];svg.setAttribute('viewBox',viewBox.join(' '))},{passive:false});svg.addEventListener('pointerdown',e=>{pointerStart=[e.clientX,e.clientY,...viewBox];dragged=false});svg.addEventListener('pointermove',e=>{if(!pointerStart)return;const dx=e.clientX-pointerStart[0],dy=e.clientY-pointerStart[1];if(Math.hypot(dx,dy)>6)dragged=true;if(dragged){const scale=Math.max(viewBox[2]/svg.clientWidth,viewBox[3]/svg.clientHeight);viewBox=[pointerStart[2]-dx*scale,pointerStart[3]-dy*scale,pointerStart[4],pointerStart[5]];svg.setAttribute('viewBox',viewBox.join(' '))}});window.addEventListener('pointerup',()=>{pointerStart=null;setTimeout(()=>dragged=false,0)});
try{if(document.modelContext?.registerTool)Promise.resolve(document.modelContext.registerTool({name:'configure_house_view',title:'Configure house view',description:'Select existing/proposed, floor and architecture/service view. Does not approve construction.',inputSchema:{type:'object',properties:{view:{type:'integer',minimum:0,maximum:8},floor:{type:'integer',enum:[0,1]},scheme:{type:'string',enum:['existing','proposed']}},required:['view'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:async input=>{if(!input||!Number.isInteger(input.view)||input.view<0||input.view>8||input.floor!==undefined&&![0,1].includes(input.floor)||input.scheme!==undefined&&!['existing','proposed'].includes(input.scheme))throw new Error('Invalid house view');state.view=input.view;state.selected=null;if(state.view===2){state.scope='all';state.explode=false}if(input.floor!==undefined)state.floor=input.floor;if(input.scheme)state.scheme=input.scheme;state.sub='plan';render();return {view:titles[state.view],floor:state.floor,scheme:state.scheme,status:'concept review'};}})).catch(()=>{})}catch{}
render();

function renderLiveElectrical(){
 const networkView=state.view===5;$('#threeWrap').hidden=true;$('#planWrap').hidden=true;$('#documentView').hidden=false;$('.workspace').classList.add('documentmode');$('#viewtitle').textContent=networkView?'Live network drawing':'Live electrical drawing';$('#sheet').textContent=networkView?'N-01 · EDITOR DESIGN':'E-01 · EDITOR DESIGN';$('#legend').hidden=true;$('#source').closest('label').hidden=true;$('#dimensions').closest('label').hidden=true;$('#units').closest('label').hidden=true;
 $('#extraControls').innerHTML='<a class="studioLink" href="studio.html">Place hardware / edit connections ↗</a><p class="footnote">These drawings read the design saved by the editor in this browser. Use Export / Import to transfer work between addresses or devices.</p><button id="liveAll">Show all rooms</button>';$('#extraControls').onchange=null;$('#liveAll').onclick=()=>{state.selected=null;render(false);};
 $('#routeTabs')?.remove();$('.drawinghead').insertAdjacentHTML('afterend',`<div class="subnav" id="routeTabs">${[['plan','Floor points'],['ceiling','Ceiling points'],['diagram','DB / circuits'],['register','Point / switch schedules']].map(([id,label])=>`<button data-sub="${id}" class="${state.sub===id?'active':''}">${label}</button>`).join('')}</div>`);
 try{const raw=localStorage.getItem('myhome-electrical-studio-v1'),p=raw?ensureDesign(JSON.parse(raw)):electricalProject(),s=calculateElectrical(p);let content;
  if(state.sub==='register')content=liveTable(pointHeaders,pointRows(p,s).filter(row=>row[3]===(state.floor?'First':'Ground')))+'<h3>Switch relationships</h3>'+liveTable(controlHeaders,controlRows(p,s));
  else if(state.sub==='diagram')content=liveTopology(p,s);
  else content=liveDrawing(p,s,{floor:state.floor,roomId:state.selected,kind:state.sub==='ceiling'?'ceiling':'plan',domain:networkView?'data':null});
  $('#documentView').innerHTML=`<div class="callout">Revision ${p.revision} · ${raw?'Your saved editor design':'Starting proposal; open the editor to customise'} · ${s.warnings.length} items need review. <a href="studio.html?tab=drawings">Open drawings and engineer pack</a></div>${content}`;$('#details').innerHTML=`<h2>One design, live schedules</h2><p>${p.points.length} placed points · ${s.circuits.length} proposed circuits · ${s.controls.length} switch links.</p><p>Ground-floor power returns to the ground DB. First-floor power returns to the first-floor DB. RJ45 runs return to the selected network rack.</p><p>${escapeElectrical(s.excluded)}</p>`;
 }catch(e){$('#documentView').innerHTML='<p>The saved design needs review. Open the electrical editor to recover or import it.</p>';}
 $('#hint').textContent='Live coordination drawing · generic hardware and traced geometry · professional installation design required';
}
window.addEventListener('storage',e=>{if(e.key==='myhome-electrical-studio-v1'&&[3,5].includes(state.view))render(false);});
window.addEventListener('focus',()=>{if([3,5].includes(state.view))render(false);});

function showSavedFixtures(){
 try{const raw=localStorage.getItem('myhome-electrical-studio-v1'),p=raw?ensureDesign(JSON.parse(raw)):electricalProject();
  const ps=(state.scheme==='proposed'?p.points:[]).map(q=>{const [x,,z]=electricalWorldPoint(q),rr=electricalRooms.find(r=>r.id===q.roomId);return {...q,x,z,floor:rr.floor,domain:['data','poe','speaker','avpath'].includes(electricalTypes[q.type].group)||q.type==='rack'?'data':'power'};});
  const rr=electricalRooms.find(r=>r.id===state.selected)||electricalRooms.find(r=>r.id===(state.floor?'f-living':'g-living'));
  model.services(ps,[],p.db,{scope:state.scope,floor:state.floor,roomOnly:false,roomId:rr.id,room:rr,rooms:electricalRooms,routes:false,ceiling:false,floorOffsets:[0,state.heights[0]+(state.view===1&&state.explode?2.5:0)]},id=>{const q=p.points.find(q=>q.id===id);if(!q)return;$('#details').innerHTML=`<span class="tag">${escapeElectrical(q.tag)} · generic hardware</span><h2>${escapeElectrical(q.label)}</h2><p>${escapeElectrical(electricalTypes[q.type].name)} · ${q.height.toFixed(2)} m above finished floor</p><p>${q.inverter?'Inverter-selected':'Normal / separate service'} · ${q.watts} W example each</p><a class="studioLink" href="studio.html?room=${encodeURIComponent(q.roomId)}&point=${encodeURIComponent(q.id)}">Move or edit this hardware ↗</a>`;});
 }catch(e){console.warn('Saved electrical hardware needs review in the editor.');}
}
window.addEventListener('storage',e=>{if(e.key==='myhome-electrical-studio-v1'&&[1,2].includes(state.view)&&model)showSavedFixtures();});
