// Room labels are transcribed from lagari plan.pdf. Units confirmed by owner.
// Geometry is traced from the discussion drawing; it is not a surveyed CAD model.
export const meta={location:'Kummil, Kerala, India',area:[1205,867],total:2072,width:8.60,depth:12.85,scale:74,origin:[[44,40],[67,40]],heights:[3.0,3.0],slab:.16};
const room=(id,name,dim,rect,kind='room',extension=false)=>({id,name,dim,rect,kind,extension});
export const rooms=[[
 room('g-work','Work area',[1.56,3.48],[55,52,116,257],'utility'),
 room('g-kitchen','Kitchen',[2.62,3.48],[184,52,194,257],'kitchen'),
 room('g-bed-rear','Rear bedroom',[3.73,3.47],[391,52,277,257],'bed'),
 room('g-dining','Dining',[3.45,3.36],[55,322,256,249],'living'),
 room('g-prayer','Prayer room',[2.47,1.80],[485,322,183,134],'prayer'),
 room('g-wc-common','Common toilet',[1.47,1.88],[559,483,109,140],'wet'),
 room('g-living','Living room',[4.36,3.45],[55,582,323,256],'living'),
 room('g-wc-front','Front ensuite',[2.64,1.53],[473,638,195,114],'wet'),
 room('g-bed-front','Front bedroom',[3.75,2.97],[391,765,277,220],'bed'),
 room('g-sitout','Sitout',[4.54,1.90],[44,849,334,141],'outdoor')
],[
 room('f-wc-rear','New rear bathroom',[3.13,1.50],[78,223,232,111],'wet',true),
 room('f-bed-rear','Rear bedroom',[3.13,3.55],[78,350,232,263],'bed'),
 room('f-laundry','New laundry',[1.60,1.80],[412,323,119,133],'utility',true),
 room('f-living','Family living',[3.34,2.80],[78,627,247,207],'living'),
 room('f-wc-front','Front ensuite',[2.64,1.53],[495,638,195,114],'wet'),
 room('f-bed-front','Front bedroom',[3.75,2.97],[413,765,277,220],'bed'),
 room('f-balcony','Balcony',[4.54,1.90],[67,849,334,141],'outdoor')
]];
// Wall centerline endpoints in source crop pixels. Openings preserved; heights provisional.
export const walls=[[
 [49,51,49,830],[55,45,171,45],[178,45,304,45],[170,51,170,235],[182,45,182,235],
 [55,315,181,315],[384,46,384,321],[391,45,668,45],[674,51,674,620],[483,315,668,315],[478,320,478,389],
 [379,462,668,462],[551,468,551,560],[558,468,558,623],[465,631,668,631],[466,635,466,750],[473,757,610,757],
 [49,840,302,840],[384,751,384,990],[668,641,668,985],[391,990,668,990]
],[
 [72,222,72,829],[78,216,310,216,1],[316,223,316,621],[141,339,310,339,1],
 [78,620,241,620],[406,315,532,315,1],[406,321,406,359,1],[536,322,536,455,1],[412,461,532,461,1],
 [402,467,690,467],[697,475,697,623],[485,631,690,631],[486,638,486,750],[495,757,632,757],
 [78,840,325,840],[405,752,405,990],[697,640,697,990],[413,990,690,990]
]];
export const windows=[[[508,990,599,990],[49,128,49,232],[49,415,49,475],[49,653,49,725],[104,840,244,840],[674,145,674,227],[496,45,571,45],[674,355,674,421],[668,679,668,719],[668,819,668,902]],[[490,990,626,990],[72,424,72,536],[72,692,72,755],[146,840,267,840],[697,821,697,904],[697,679,697,719],[697,510,697,570]]];
export const ideas={
 'g-living':{title:'A sculpted living spine',text:'Replace the bulky L-shaped seating with a 2.30 × 0.90 m straight sofa on the left wall, a compact oval table and one movable chair. Retain the photographed beam, pier and pass-through frame. A removable media insert and 1.60 × 0.35 m console can occupy the existing opening.',detail:'Keep the right circulation lane open. Target 0.95 m clear after furniture; verify at the narrowest point. Use rounded applied finishes and an accessible LED recess; do not enlarge the opening or remove the existing pier/beam without structural approval.',services:'Place TV power, two data runs and an empty media conduit at the new console. Plan sofa-side power and curtain wiring before plastering.'},
 'g-dining':{title:'A quieter dining alcove',text:'A 1.40 × 0.80 m four-to-six seat table works with a shallow storage bench at the left edge. A softly lit plaster panel can frame the dining zone without closing it off.',detail:'Keep the kitchen-to-stair passage clear. Confirm chair pull-out space; the labelled 3.45 × 3.36 m rectangle does not include every circulation edge.',services:'Fix the table position before the pendant point. Put a separate lighting circuit provision at the bench and retain the wash-basin service access.'},
 'g-kitchen':{title:'One continuous working line',text:'Retain the wet wall and use coordinated full-height fronts, a tall pantry and under-cabinet task lighting. Keep the 1.56 m work area useful for washing and service access.',detail:'Try a 0.60 m counter and no more than 0.35 m shallow storage opposite in the 2.62 m kitchen: about 1.67 m nominal gap before projections. Final appliance and cabinet drawings govern.',services:'Separate cooking appliance, oven, dishwasher, refrigerator and general counter circuits as the final appliance list requires. Reserve dishwasher water, trapped waste and accessible isolation near the wet zone.'},
 'g-prayer':{title:'A calm, light-lined niche',text:'Use a freestanding or surface-built storage panel, a warm wall wash and a removable screen at the existing opening. Keep ritual orientation and storage choices owner-led.',detail:'Do not assume religious orientation from the PDF compass. Keep ventilation and floor access unobstructed.',services:'Provide a discreet lighting switch and accessible driver location outside closed joinery.'},
 'f-living':{title:'A family lounge that can work harder',text:'Use a 2.00 m straight sofa and a 1.20 × 0.45 m desk/media ledge. A sliding furniture screen can create a study corner without adding a masonry partition.',detail:'This is a 3.34 × 2.80 m room: avoid a second deep sofa. Protect the route to balcony, stairs and rear bedroom.',services:'Provide desk outlets, two data points, independent task light, curtain provision and future AC sleeve/drain.'},
 'f-laundry':{title:'An accessible service cupboard',text:'Plan a stacked washer/dryer, a shallow utility sink where clearances allow, and washable finishes. The laundry enclosure is a new addition, not an existing room.',detail:'Confirm appliance clearance, vibration, ventilation, waterproofing, slab loading and approved enclosure layout before construction.',services:'Accessible cold-water isolation, trapped standpipe and cleanout, leak sensor, separate washer/dryer electrical provision. Keep sockets and isolation clear of splash zones.'},
 'f-wc-rear':{title:'Build the bathroom around its drain',text:'Arrange fixtures only after the waste exit and floor build-up are resolved. Keep a surface-mounted service wall for cistern and pipe access where space permits.',detail:'This addition sits above the rear service/kitchen side in the concept. Do not assume its waste can reach the front stack by a long hidden horizontal run.',services:'Investigate a dedicated accessible rear stack with vent continuation, trap protection and inspection access. Confirm invert levels and slab penetrations before work.'}
};
export function ideaFor(r){return ideas[r.id]|| (r.kind==='bed'?{title:'More room through fitted edges',text:'Use a 1.50 × 2.00 m bed, a 0.60 m deep wardrobe where the plan shows storage, and shallow bedside shelves. A soft plaster headboard plane and warm wall lights replace heavy decorative panelling.',detail:'Check wardrobe door travel and bedside circulation against actual wall faces. Existing window sizes and sill levels need measurement.',services:'Bedside switching on both sides, desk/data provision, dedicated future AC with drain and sleeve, and curtain motor conduit.'}:r.kind==='wet'?{title:'Keep the wet core serviceable',text:'Retain the main fixture zone and concentrate pipework in an accessible service wall or shaft. Use coordinated matte tile and a removable mirror cabinet.',detail:'Fixture arrangement, wet-zone electrical restrictions, waterproofing height and floor falls require a detailed bathroom layout.',services:'Hot/cold supply, accessible local isolation, trapped and vented drainage, water-heater provision, exhaust point and leak sensor.'}:r.kind==='outdoor'?{title:'A shaded threshold',text:'Unify the sitout and balcony with a restrained plaster frame, slim screen and warm wall wash. Planters should have their own liners and drainage.',detail:'New screens and canopies require wind and fixing design. Keep guards compliant and prevent rainwater discharge onto paths.',services:'Weather-suitable light, socket and CCTV/data provision; keep rainwater separate from foul drainage.'}:{title:'Practical concealed services',text:'Keep working clearances and accessible shutoffs. Use shallow, removable joinery panels for maintenance.',detail:'Agree finished cabinet lines and material transitions before marking service points.',services:'Dedicated appliance provisions, accessible isolation and documented pipe/conduit routes.'});}
export const colors={electric:'#b87908',cold:'#078ace',hot:'#dc4a47',waste:'#82624a',network:'#7544be',future:'#0a9286',extension:'#cc36c9'};
export const point=(id,type,x,y,name,note)=>({id,type,x,y,name,note});
// New point proposals, not transcriptions of installed services. Pixel positions are indicative.
export const electrical=[[
point('DB-G','DB',374,442,'Ground distribution board','Proposed accessible dry circulation location. Confirm approach space, fire/escape constraints and incoming route.'),
point('L-G1','L',210,680,'Living lighting','Ambient + wall wash + reading circuit groups; accessible LED drivers.'),point('L-G2','L',210,445,'Dining pendant','Set over final table; keep fan blade and pendant clearances.'),point('L-G3','L',292,175,'Kitchen task light','Ceiling and under-cabinet switching.'),point('L-G4','L',535,187,'Rear bedroom light/fan','Separate controls; ceiling structure/anchor to verify.'),point('L-G5','L',529,858,'Front bedroom light/fan','Bedside switching provision.'),point('L-G6','L',579,390,'Prayer light','Warm wall wash.'),point('L-G7','L',115,170,'Work area light','Humidity-suitable fitting.'),point('L-G8','L',620,555,'Common toilet light/exhaust','Wet-zone layout and IP class by designer.'),point('L-G9','L',565,690,'Ensuite light/exhaust','Coordinate mirror, exhaust and ceiling.'),point('L-G10','L',238,930,'Sitout light','Weather exposure to verify.'),
point('S-G1','S',120,598,'Media wall power','Revised media position. General outlets plus separate data conduits.'),point('S-G2','S',75,759,'Sofa outlet','Final height to furniture; keep accessible.'),point('S-G3','S',286,79,'Kitchen appliances','Separate circuit routes; final appliance schedule required.'),point('S-G4','S',197,264,'Dishwasher / purifier reserve','Accessible sink-zone services; no socket below leak-prone joints.'),point('S-G5','S',95,270,'Work-area appliance','Separate washer provision if used here.'),point('S-G6','S',640,260,'Rear bed sockets','Both bedside positions and study outlet.'),point('S-G7','S',622,951,'Front bed sockets','Both bedside positions and study outlet.'),
point('AC-G1','AC',650,110,'Rear bedroom AC reserve','Dedicated circuit, accessible outdoor isolator, sleeve and separately designed condensate drain.'),point('AC-G2','AC',650,809,'Front bedroom AC reserve','Same requirements; capacity after cooling-load calculation.'),point('AC-G3','AC',72,651,'Living AC reserve','Check throw and outdoor-unit access.'),point('WH-G1','WH',626,646,'Front water heater provision','Electrical isolator in permitted dry zone; pressure/temperature relief discharge must remain unobstructed.'),point('WH-G2','WH',642,493,'Common toilet heater reserve','Only if this room will have bathing fixtures; layout confirmation required.'),point('EV-R','R',350,1007,'Gate / EV future route','Indicative front exit only; gate and parking position unmeasured. Dedicated empty route with draw cord.'),point('PV-R','R',368,80,'Roof / future floor route','Accessible vertical riser. Separate PV DC, mains AC and data pathways as designed.')
],[
point('DB-F','DB',374,590,'First-floor distribution board','Accessible dry landing; maintain stair egress.'),point('L-F1','L',188,463,'Rear bedroom light/fan','Bedside switching.'),point('L-F2','L',188,701,'Family lounge lighting','Ambient and desk light groups.'),point('L-F3','L',550,853,'Front bedroom light/fan','Separate controls.'),point('L-F4','L',567,694,'Ensuite light/exhaust','Wet-zone compliant positions.'),point('L-F5','L',192,280,'New bathroom light/exhaust','New work; complete fixture plan first.'),point('L-F6','L',470,385,'Laundry light','Humidity and access clearance.'),point('L-F7','L',237,935,'Balcony light','Weather-suitable fitting.'),point('L-F8','L',520,155,'Terrace light','Access and glare review.'),point('S-F1','S',97,653,'Study/media power','Two data runs alongside separate electrical provision.'),point('S-F2','S',100,557,'Rear bed sockets','Both bedside positions.'),point('S-F3','S',651,951,'Front bed sockets','Both bedside positions.'),point('S-F4','S',452,432,'Laundry appliances','Washer and dryer separate provisions as nameplates require.'),point('AC-F1','AC',93,410,'Rear bedroom AC reserve','Dedicated power + sleeve + condensate.'),point('AC-F2','AC',677,810,'Front bedroom AC reserve','Dedicated power + sleeve + condensate.'),point('AC-F3','AC',94,734,'Family lounge AC reserve','Outdoor-unit position and access to verify.'),point('WH-F1','WH',272,245,'New bathroom heater','Hot-water source strategy not yet selected.'),point('WH-F2','WH',653,651,'Front bathroom heater','Isolator and relief discharge layout by installer.'),point('PV-F','R',363,139,'Solar / future riser','Space reservation only; no roof panel layout without roof survey.')
]];
export const plumbing=[[
point('P-G1','CW',203,195,'Kitchen sink / dishwasher / purifier','Cold + optional hot to sink, separate accessible appliance branches; purifier reject to approved trapped arrangement.'),point('P-G2','CW',76,195,'Work sink','Cold/hot as needed; local isolation.'),point('P-G3','CW',72,352,'Dining wash basin','Keep waste accessible at rear service side.'),point('P-G4','CW',641,534,'Common toilet','WC cold feed; bathing hot-water requirement to confirm.'),point('P-G5','CW',493,693,'Front ensuite','Hot/cold fixtures and WC cold feed; local valves.'),point('ST-A','ST',706,682,'Front soil/vent stack A','Outside the front bathroom wet zone; route not a confirmed setback position.'),point('ST-B','ST',21,257,'Rear soil/vent stack B','Candidate dedicated stack for new upstairs bathroom. Survey outside clearance and foul discharge destination.'),point('CW-R','R',17,86,'Cold/hot risers','Concept rear service zone. Well and utility sources kept independent if required.'),point('RAIN-G','RW',715,100,'Rainwater downpipe reserve','A separate stormwater system; outlet and catchment calculation pending.')
],[
point('P-F1','CW',272,273,'New bathroom fixtures','Cold, hot where needed, trapped/vented waste and local isolation.'),point('P-F2','CW',436,439,'Laundry washer / sink','Cold feed, accessible shutoff, trapped standpipe and leak sensor.'),point('P-F3','CW',514,693,'Front ensuite','Retain stacked wet core where verified.'),point('ST-A','ST',726,682,'Front soil/vent stack A','Vertical link to ground; vent termination and clearances by design.'),point('ST-B','ST',41,257,'Rear soil/vent stack B','New rear bathroom discharge to dedicated accessible riser; structural penetration approval required.'),point('CW-R','R',40,87,'Water / future hot-water riser','Insulated hot-water route provision, controlled future connection near service zone.'),point('RAIN-F','RW',726,100,'Terrace rainwater route','Primary drain plus safe overflow; location after roof level survey.')
]];
export const network=[[
point('RACK','RK',343,420,'Ventilated network cabinet','Accessible dry central location, dedicated backed-up power, patch panel, router/ONT, PoE switch and labelled reserve routes.'),point('AP-G','AP',350,610,'Ground ceiling Wi-Fi AP','Wired PoE feed; validate coverage on site.'),point('D-G1','D',145,591,'Living media data','Two Cat6A runs recommended if 10 Gb/s full-channel target.'),point('D-G2','D',415,260,'Rear bedroom desk','Two home runs; avoid CCA conductors.'),point('D-G3','D',416,795,'Front bedroom desk','Two home runs.'),point('CAM-G1','C',67,869,'Entrance camera','Provisional line of sight; avoid filming private neighbouring areas.'),point('CAM-G2','C',647,65,'Rear approach camera','PoE with weather-suitable termination.'),point('ISP-R','R',349,1003,'ISP / gate / intercom route','Empty draw-cord ducts, separate from mains; entry point to confirm.')
],[
point('RISER','RK',374,589,'Data riser from ground rack','Separate continuous data/fibre path with accessible pull points.'),point('AP-F','AP',373,690,'First-floor ceiling Wi-Fi AP','PoE. An additional AP is optional after coverage check.'),point('D-F1','D',108,654,'Family desk/media data','Two home runs to ground rack.'),point('D-F2','D',100,405,'Rear bedroom desk','Two home runs.'),point('D-F3','D',435,795,'Front bedroom desk','Two home runs.'),point('CAM-F','C',95,865,'Balcony approach camera reserve','Confirm coverage and privacy.'),point('D-ROOF','R',361,151,'Roof / future-floor data reserve','Empty spare pathway; weather sealed ends.')
]];
export const circuits=[
['E01','Ground lighting / fans','Split front and rear groups; preserve light when one group trips.'],['E02','First-floor lighting / fans','Split bedroom and circulation groups.'],['E03','General sockets by floor/zone','Final outlet count and diversity to be calculated.'],['E04','Kitchen counter circuits','More than one final circuit as demand requires.'],['E05','Cooking / oven','Separate appliance circuits according to nameplate and installation rules.'],['E06','Dishwasher / washer / dryer','Reserve distinct appliance routes and accessible isolation.'],['E07','Each AC unit','Seven reserved locations: four bedrooms, two living rooms and prayer room; capacity and circuits after design.'],['E08','Each water heater','Three bathrooms plus optional common-toilet reserve; confirm bathing use.'],['E09','Pump / outdoor / gate','Separate functions with suitable motor and environmental protection.'],['E10','Fridge / network / selected essential lights','Proposed backup group; actual backup capacity to be designed.'],['E11','Future solar / battery / EV / upper floor','Reserve pathways and panel capacity; do not preselect ratings.']
];
export const checklist=[
 ['Moisture before finishes','Photographs show staining and finish deterioration. Establish rain/roof, plumbing or other moisture sources; repair and verify dryness before new plaster, joinery or painting. Photograph findings and agree the remediation method.','Site professional / waterproofing and plumbing teams'],
['Survey','Measure wall faces, diagonals, floor-to-floor heights, door/window openings, sill levels, stair geometry and structural members.','Architect / site supervisor'],
['New additions','Approve the pink bathroom and laundry additions, slab loading, waterproofing, ventilation and all penetrations.','Architect / structural engineer'],
['Furniture first','Mark beds, wardrobes, revised media wall, sofa, dining table, study desk and exact appliance footprints on site.','Owner / interior designer'],
['Electrical calculations','Final load schedule, supply phase/capacity, cable derating and voltage drop, fault level, protective coordination, earthing and surge assessment.','Licensed electrical contractor / designer'],
['No hidden dead ends','Dry conduits with draw cords and accessible pull points; neutral and protective conductor provisions at compatible smart-switch boxes.','Electrical contractor'],
['Future routes','Approve distinct spare routes to roof, gate/parking, each AC location, network cabinet and future floor; label and photograph both ends.','Services coordinator'],
['Water strategy','Confirm utility/well quality, treatment, storage, pressure, hot-water source and backflow protection; keep sources segregated where required.','Plumbing designer'],
['Drainage levels','Confirm final sanitary destination, invert levels, pipe sizes/falls, trap protection, vent terminations and cleanout access.','Plumbing designer'],
['Rough plumbing test','Hydrostatic test with water after full joint cure, using selected manufacturer pressure/duration limits. Record results before covering.','Plumbing contractor'],
['Waterproofing','Complete approved waterproofing details, pipe collars and upstands; flood-test to system specification before tiling.','Waterproofing contractor'],
['Rain and condensate','Verify primary rainwater discharge, safe overflow and separate AC condensate falls/cleaning access.','Plumbing / AC contractor'],
['Electrical verification','At suitable installation stages: continuity, insulation, polarity, earth fault loop/earthing and instrumented RCD tests; protect electronics during testing.','Licensed electrical contractor'],
['Network verification','Label both ends, certify installed cabling for selected category and verify PoE loads and AP locations.','Data installer'],
['Record and release','Photograph every wall with scale and datum; record route offsets, valves, joints and sleeves. Obtain dated written release before plastering/closing.','All trades + owner']
];
