import {allRooms,roomById,byType,origin,worldPoint,isBoard,isSwitch} from './studio-data.js?v=20260913-layout-2';
export const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const tag=(p,id)=>p.points.find(q=>q.id===id)?.tag||'UNASSIGNED';
const name=(p,id)=>p.points.find(q=>q.id===id)?.label||'No source';
const colors={power:'#b1652c',essential:'#007e6b',data:'#7954b0',control:'#32859c',reserve:'#87936c',feeder:'#c34c4c'};
export function drawing(project,stats,{floor=0,roomId=null,kind='plan',surface='A',domain=null}={}){
  const room=roomById[roomId],elevation=kind==='wall'&&room;
  const list=project.points.filter(p=>roomById[p.roomId].floor===floor&&(!roomId||p.roomId===roomId)&&(kind!=='ceiling'||p.surface==='ceiling')&&(!elevation||p.surface===surface)&&(!domain||['rj45','rj45single','rack','ap','camera','intercom','hdmi','speaker'].includes(p.type)));
  const floorRooms=allRooms.filter(r=>r.floor===floor&&(!roomId||r.id===roomId));
  const W=1000,H=elevation?590:1140,title=`${floor?'FIRST':'GROUND'} FLOOR · ${elevation?'SURFACE '+surface:kind==='ceiling'?'CEILING POINTS':domain==='data'?'NETWORK POINTS':'ELECTRICAL POINTS'}`;
  let body=`<rect width="${W}" height="${H}" fill="white"/><text x="35" y="32" font-size="20" font-weight="700">${title}</text><text x="35" y="52" font-size="11">Revision ${project.revision||1} · metres · concept coordination · verify on site</text>`;
  const projectXY=p=>{const [x,,z]=worldPoint(p);if(elevation){const axis=['B','D'].includes(surface)?p.v:p.u;return [65+axis*150,490-p.height*140];}return [95+(x+1)*47,75+z*47];};
  if(elevation){const width=['B','D'].includes(surface)?room.dim[1]:room.dim[0];body+=`<rect x="65" y="${490-2.84*140}" width="${width*150}" height="${2.84*140}" fill="#f5f7f3" stroke="#52675a"/><text x="65" y="525" font-size="13">${esc(room.name)} · ${width.toFixed(2)} m wide · 2.84 m model ceiling</text>`;}
  else{
    for(const r of floorRooms){const [x,z]=origin(r),[w,d]=r.dim;body+=`<rect x="${95+(x+1)*47}" y="${75+z*47}" width="${w*47}" height="${d*47}" fill="${r.kind==='site'?'#f5f2e9':'#f3f6f1'}" stroke="#657969" stroke-width="2"/><text x="${99+(x+1)*47}" y="${88+z*47}" font-size="10" fill="#657969">${esc(r.name)}</text><text x="${99+(x+1)*47}" y="${100+z*47}" font-size="9" fill="#7e8a80">${w.toFixed(2)} × ${d.toFixed(2)} m</text>`;}
    for(const route of stats.routes.filter(r=>list.some(p=>p.id===r.pointId))){if(domain==='data'&&route.domain!=='data')continue;const poly=route.points.map(([x,,z])=>`${95+(x+1)*47},${75+z*47}`).join(' ');body+=`<polyline points="${poly}" fill="none" stroke="${colors[route.domain]}" stroke-width="1" opacity=".5" ${route.domain==='control'?'stroke-dasharray="4 4"':''}/>`;}
  }
  for(const p of list){const [x,y]=projectXY(p),color=p.type.includes('rj45')||p.type==='rack'?'#7954b0':p.inverter?'#007e6b':'#b1652c';let shape=isBoard(p)||p.type==='rack'?`<rect x="${x-7}" y="${y-9}" width="14" height="18" fill="white" stroke="${color}" stroke-width="2"/>`:p.type==='fan'?`<circle cx="${x}" cy="${y}" r="9" fill="white" stroke="${color}"/><path d="M${x-7} ${y}h14M${x} ${y-7}v14" stroke="${color}"/>`:isSwitch(p)?`<rect x="${x-4}" y="${y-4}" width="8" height="8" fill="${color}"/>`:`<circle cx="${x}" cy="${y}" r="4" fill="${color}"/>`;body+=`<g><title>${esc(p.tag+' · '+p.label+' · '+p.height.toFixed(2)+' m AFF')}</title>${shape}<text x="${x+7}" y="${y-6}" font-size="9" fill="#283a31">${esc(p.tag)}</text></g>`;}
  const lx=720;body+=`<text x="${lx}" y="95" font-size="14" font-weight="700">POINT / SOURCE LEGEND</text>`;
  [['power','Normal power'],['essential','Inverter-selected'],['data','Data to rack'],['control','Functional switch link'],['feeder','DB feeder concept']].forEach(([d,t],i)=>{body+=`<path d="M${lx} ${118+i*24}h24" stroke="${colors[d]}" stroke-width="3"/><text x="${lx+34}" y="${122+i*24}" font-size="12">${t}</text>`;});
  body+=`<text x="${lx}" y="270" font-size="12">Ground DB: ${esc(tag(project,project.dbIds[0]))}</text><text x="${lx}" y="292" font-size="12">First DB: ${esc(tag(project,project.dbIds[1]))}</text><text x="${lx}" y="314" font-size="12">Network rack: ${esc(tag(project,project.rackId))}</text><text x="35" y="${H-55}" font-size="11">${list.length} points shown · Source relationships and independent route estimates; see schedules for heights, loads and connections.</text><text x="35" y="${H-34}" font-size="11">Not a terminal wiring diagram. Traced geometry, crossings, conduit fill, cable sizes and structural clearance require engineering review.</text>`;
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${W} ${H}" class="electrical-sheet" role="img" aria-label="${title}" style="font-family:Arial,sans-serif;color:#26392f">${body}</svg>`;
}
export function topology(project,stats){
  const cs=stats.circuits,H=Math.max(300,cs.length*42+110);let body=`<rect width="1100" height="${H}" fill="white"/><text x="20" y="30" font-size="20">LIVE DISTRIBUTION · revision ${project.revision||1}</text><text x="20" y="53" font-size="12">Sources → proposed circuit groups → equipment references. Control schedule defines switch relationships.</text>`;
  cs.forEach((c,i)=>{const y=85+i*42,color=c.essential?colors.essential:colors.power;body+=`<text x="20" y="${y}" font-size="12">${esc(tag(project,c.sourceId)+' '+name(project,c.sourceId))}</text><path d="M220 ${y-4}h30" stroke="${color}"/><rect x="250" y="${y-18}" width="170" height="29" rx="4" fill="${color}"/><text x="261" y="${y}" fill="white" font-size="12">${esc(c.id+' · '+c.phase+' · '+c.watts.toFixed(0)+' W')}</text><path d="M420 ${y-4}h25" stroke="${color}"/><text x="455" y="${y}" font-size="11">${esc(c.points.map(id=>tag(project,id)).join(', '))}</text>`;});
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1100 ${H}" class="electrical-sheet" role="img" aria-label="Live source and circuit diagram" style="font-family:Arial,sans-serif">${body}</svg>`;
}
export const table=(headers,rows)=>`<table><thead><tr>${headers.map(h=>`<th>${esc(h)}</th>`).join('')}</tr></thead><tbody>${rows.map(row=>`<tr>${row.map(v=>`<td>${esc(v)}</td>`).join('')}</tr>`).join('')}</tbody></table>`;
export function pointRows(project,stats){return project.points.map(p=>{const circuit=stats.circuits.find(c=>c.points.includes(p.id)),route=stats.routes.find(r=>r.id===p.id);return [p.tag,p.label,byType[p.type].name,roomById[p.roomId].floor?'First':'Ground',roomById[p.roomId].name,p.surface,p.u.toFixed(2),p.v.toFixed(2),p.height.toFixed(2),p.qty,p.watts,byType[p.type].group==='data'?'Data only':byType[p.type].group==='poe'?'Via rack supply':p.inverter?'Essential':'Normal',route?tag(project,route.sourceId):isBoard(p)?'Distribution':isSwitch(p)?'See control schedule':'UNROUTED / separate service',circuit?.id||'—'];});}
export const pointHeaders=['Ref','Name','Hardware','Floor','Room','Surface','Across m','From rear m','AFF m','Qty','W each','Supply','Source','Circuit'];
export const controlRows=(p,s)=>s.controls.map(c=>[tag(p,c.switchId),c.switchName,tag(p,c.loadId),c.loadName,c.circuitId,c.multiway?'Multiple control locations':'Single control location',c.length.toFixed(2),'Functional only; terminal design pending']);
export const controlHeaders=['Switch','Switch name','Load','Load name','Load circuit','Control arrangement','Route m','Status'];
export function engineerPack(project,stats,bom){
 const title=`My home · electrical coordination · R${project.revision||1}`;
 const circuits=stats.circuits.map(c=>[c.id,tag(project,c.sourceId),c.floor?'First':'Ground',c.phase,c.essential?'Essential':'Normal',c.watts.toFixed(0),c.points.map(id=>tag(project,id)).join(', '),c.length.toFixed(2),project.wireSpecs?.[c.key]||'Unassigned']);
 const routes=stats.routes.map(r=>[r.id,tag(project,r.sourceId),tag(project,r.pointId),r.domain,r.length.toFixed(2),r.points.map(v=>v.map(n=>n.toFixed(2)).join(',')).join(' → ')]);
 return `<!doctype html><html><head><meta charset="utf-8"><title>${esc(title)}</title><style>body{font:13px/1.45 Arial;color:#26392f;margin:30px}h1{font-size:27px}h2{margin-top:35px}table{border-collapse:collapse;width:100%;font-size:10px}td,th{border:1px solid #ccd5cc;padding:6px;text-align:left;overflow-wrap:anywhere}th{background:#eef4ee}.electrical-sheet{width:100%;height:auto;max-height:1050px}section{break-before:page}tr{break-inside:avoid}.warn{padding:14px;background:#fff3db}@page{size:A3 landscape;margin:12mm}@media print{button{display:none}body{margin:0}.electrical-sheet{max-height:245mm}}</style></head><body><button onclick="print()">Print / save as PDF</button><h1>${esc(title)}</h1><p>Generated ${esc(new Date().toISOString())}. Model floor height: 3.00 m; assumed clear ceiling 2.84 m. Coordinates are metres from each room's rear-left inside corner. Hardware models and dimensions are generic samples.</p><div class="warn"><b>Engineering review required before construction or purchasing.</b> ${esc(stats.excluded)}<br>Final-circuit conductor and conduit totals are independent-route allowances, not a coordinated installation takeoff.</div><h2>Items needing resolution (${stats.warnings.length})</h2><ul>${stats.warnings.map(w=>`<li>${esc(w)}</li>`).join('')||'<li>No missing source or switch assignment warnings. Engineering checks still apply.</li>'}</ul>${[0,1].map(f=>`<section>${drawing(project,stats,{floor:f})}</section><section>${drawing(project,stats,{floor:f,kind:'ceiling'})}</section>`).join('')}<section><h2>Point and mounting schedule</h2>${table(pointHeaders,pointRows(project,stats))}</section><section><h2>Sources and proposed circuits</h2>${table(['Circuit','DB','Floor','Phase','Supply','W','Points','Route m','Wire mm² (user assigned)'],circuits)}</section><section><h2>Switch-to-load connections</h2><p>Multiple rows for one switch indicate one control channel serving multiple compatible loads. Multiple switches for one load indicate a multi-location control requirement. The electrician must select and draw the switching / relay topology. Separate normal, essential and different DB circuits are never joined by this tool.</p>${table(controlHeaders,controlRows(project,stats))}</section><section><h2>Material estimate</h2>${table(['Material','Quantity','Unit','Basis'],bom.map(b=>[b.name,b.qty.toFixed(2),b.unit,b.note]))}</section><section><h2>Concealed route coordinate schedule</h2><p>World coordinates are x,y,z metres. y includes the floor elevation. Control lines are functional route allowances; floor-plan crossings do not mean electrical junctions.</p>${table(['Route','From','To','Service','m','Coordinates x,y,z'],routes)}</section></body></html>`;
}
