import {allRooms,roomById,byType,isSwitch,isLoad} from './studio-data.js?v=20260913-structure-navigation-1';
import {emergencyEligible,emergencyGroup,emergencyWatts,setEmergency,switchChoice,assignSwitchLoads} from './power-controls.js?v=20260913-structure-navigation-1';
import {esc} from './electrical-report.js?v=20260913-structure-navigation-1';
let mode='emergency',query='',floor='all',switchId='',loadRoom='all';
const kw=w=>(w/1000).toFixed(3)+' kW';
export function powerPanel(host,project,stats,hooks){
 const switches=project.points.filter(isSwitch);if(!switches.some(p=>p.id===switchId))switchId=switches[0]?.id||'';
 host.innerHTML=`<span class="tag">Power planning</span><h1>Choose your emergency equipment</h1><div class="power-summary"><div><small>Total inverter load</small><strong>${kw(stats.connectedEssential)}</strong></div><div><small>Normal supply load</small><strong>${kw(stats.connectedLoad-stats.connectedEssential)}</strong></div><div><small>Total connected</small><strong>${kw(stats.connectedLoad)}</strong></div></div><p>Tick equipment to include it on the inverter. These are entered connected watts, before diversity; runtime and starting-surge capacity are not calculated.</p><div class="buttonrow"><button data-power-mode="emergency" class="${mode==='emergency'?'active':''}">Emergency / inverter equipment</button><button data-power-mode="switches" class="${mode==='switches'?'active':''}">Switchboards & equipment</button></div><div id="powerWorkspace"></div>`;
 host.querySelectorAll('[data-power-mode]').forEach(b=>b.onclick=()=>{mode=b.dataset.powerMode;query='';powerPanel(host,project,stats,hooks);});
 const work=host.querySelector('#powerWorkspace');
 if(mode==='emergency'){
  work.innerHTML=`<h2>Emergency equipment checklist</h2><p class="subtle">Equipment sharing a switch channel changes supply together. CCTV and other PoE devices follow the selected network rack and are included once in its row.</p><div class="power-filters"><input id="emergencySearch" type="search" aria-label="Search emergency equipment" placeholder="Find lights, fans, sockets, AC…" value="${esc(query)}"><select id="emergencyFloor" aria-label="Emergency equipment floor"><option value="all">Both floors</option><option value="0">Ground floor</option><option value="1">First floor</option></select></div><div id="emergencyChoices" class="power-list"></div>`;
  const search=work.querySelector('#emergencySearch'),filter=work.querySelector('#emergencyFloor');filter.value=floor;
  const paint=()=>{const items=project.points.filter(p=>emergencyEligible(p)&&(floor==='all'||roomById[p.roomId].floor===Number(floor))&&`${p.tag} ${p.label} ${byType[p.type].name} ${roomById[p.roomId].name}`.toLowerCase().includes(query.toLowerCase()));
   work.querySelector('#emergencyChoices').innerHTML=items.map(p=>{const group=emergencyGroup(project,p.id).filter(emergencyEligible);return `<label class="power-row"><input type="checkbox" data-emergency="${p.id}" ${p.inverter?'checked':''} aria-label="Emergency ${esc(p.tag+' '+p.label)}"><span><b>${esc(p.tag+' · '+p.label)}</b><small>${roomById[p.roomId].floor?'First':'Ground'} · ${esc(roomById[p.roomId].name)}${group.length>1?' · '+group.length+' linked items follow together':''}${p.id===project.rackId?' · includes attached PoE equipment':''}</small></span><strong>${emergencyWatts(project,p).toFixed(0)} W</strong></label>`;}).join('')||'<p>No matching equipment.</p>';
   work.querySelectorAll('[data-emergency]').forEach(el=>el.onchange=()=>hooks.change(()=>setEmergency(project,el.dataset.emergency,el.checked)));
  };search.oninput=()=>{query=search.value;paint();};filter.onchange=()=>{floor=filter.value;paint();};paint();
 }else{
  const sw=project.points.find(p=>p.id===switchId),links=project.connections.filter(c=>c.switchId===switchId),assigned=project.points.filter(p=>links.some(c=>c.loadId===p.id));
  work.innerHTML=`<h2>Assign equipment to a switchboard</h2><p class="subtle">Each switch station is one control channel. Add separate switches for independent controls or different circuits. A load can have more than one control location.</p><label class="field">Switchboard / switch<select id="plannerSwitch" aria-label="Select switchboard">${switches.map(p=>`<option value="${p.id}">${esc(p.tag+' · '+p.label+' · '+roomById[p.roomId].name)}</option>`).join('')}</select></label><div class="buttonrow"><button id="locateSwitch" ${sw?'':'disabled'}>Locate in 3D</button><button id="newPlannerSwitch">+ New switch</button></div><div class="assigned-summary"><b>${assigned.length} assigned loads · ${assigned.reduce((n,p)=>n+p.watts*p.qty,0).toFixed(0)} W</b><p>${esc(assigned.map(p=>p.tag+' '+p.label).join(' · ')||'Tick equipment below to assign it.')}</p></div><div class="power-filters"><input id="switchSearch" type="search" aria-label="Search switch equipment" placeholder="Find equipment to control…" value="${esc(query)}"><select id="switchRoom" aria-label="Filter switch equipment by room"><option value="all">All areas</option>${allRooms.map(r=>`<option value="${r.id}">${esc(r.name)} · ${r.floor?'First':'Ground'}</option>`).join('')}</select></div><div class="buttonrow"><button id="linkMatching" ${sw?'':'disabled'}>Assign compatible matches</button><button id="clearSwitch" ${assigned.length?'':'disabled'}>Clear this switch</button></div><div id="plannerLoads" class="power-list"></div>`;
  work.querySelector('#plannerSwitch').value=switchId;work.querySelector('#plannerSwitch').onchange=e=>{switchId=e.target.value;powerPanel(host,project,stats,hooks);};
  work.querySelector('#locateSwitch').onclick=()=>hooks.locate(switchId);work.querySelector('#newPlannerSwitch').onclick=()=>hooks.createSwitch();
  const search=work.querySelector('#switchSearch'),filter=work.querySelector('#switchRoom');filter.value=loadRoom;
  const matches=()=>project.points.filter(p=>isLoad(p)&&p.id!==switchId&&(loadRoom==='all'||p.roomId===loadRoom)&&`${p.tag} ${p.label} ${roomById[p.roomId].name}`.toLowerCase().includes(query.toLowerCase()));
  const paint=()=>{work.querySelector('#plannerLoads').innerHTML=matches().map(p=>{const c=switchChoice(project,switchId,p);return `<label class="power-row ${c.reason?'unavailable':''}"><input type="checkbox" data-planner-load="${p.id}" ${c.checked?'checked':''} ${c.reason?'disabled':''} aria-label="Assign ${esc(p.tag+' '+p.label)}"><span><b>${esc(p.tag+' · '+p.label)}</b><small>${esc(roomById[p.roomId].name)} · ${p.inverter?'Emergency':'Normal'}${c.reason?' · '+esc(c.reason):''}</small></span><strong>${p.watts*p.qty} W</strong></label>`;}).join('')||'<p>No matching equipment.</p>';work.querySelectorAll('[data-planner-load]').forEach(el=>el.onchange=()=>hooks.change(()=>assignSwitchLoads(project,switchId,[el.dataset.plannerLoad],el.checked)));};
  search.oninput=()=>{query=search.value;paint();};filter.onchange=()=>{loadRoom=filter.value;paint();};
  work.querySelector('#clearSwitch').onclick=()=>hooks.change(()=>assignSwitchLoads(project,switchId,assigned.map(p=>p.id),false));
  work.querySelector('#linkMatching').onclick=()=>hooks.change(()=>{for(const p of matches()){const c=switchChoice(project,switchId,p);if(!c.checked&&!c.reason)assignSwitchLoads(project,switchId,[p.id],true);}});paint();
 }
}
