import {rooms,meta} from './data.js';
import {allElectrical} from './room-electrical.js';
export const library=[
 ['socket2','Twin switched socket','Power',100,'C',.45,'general'],['socket1','Single switched socket','Power',100,'B',.45,'general'],['usb','USB-C charging socket','Power',65,'C',.75,'general'],['floorbox','Floor outlet box','Power',150,'floor',.02,'general'],
 ['switch','Wall switch station','Controls',0,'D',1.10,'control'],['bedstation','Bedside switch + twin sockets','Controls',100,'C',.75,'general'],['dimmer','Dimmer / scene controller','Controls',0,'D',1.10,'control'],['sensor','Occupancy sensor','Controls',2,'ceiling',2.84,'lighting'],['curtain','Curtain motor provision','Controls',60,'A',2.35,'dedicated'],
 ['downlight','LED downlight','Lighting',9,'ceiling',2.84,'lighting'],['strip','LED strip + accessible driver','Lighting',30,'A',2.50,'lighting'],['sconce','Wall / bedside light','Lighting',6,'C',1.25,'lighting'],['night','Low-level night light','Lighting',2,'C',.30,'lighting'],['pendant','Pendant light','Lighting',15,'ceiling',2.84,'lighting'],['outdoorlight','Exterior wall light','Lighting',12,'C',2.20,'lighting'],
 ['fan','Ceiling fan','Equipment',35,'ceiling',2.84,'lighting'],['exhaust','Exhaust fan','Equipment',25,'A',2.30,'lighting'],['ac','AC unit + isolation provision','Equipment',1500,'B',2.10,'dedicated'],['pc','PC workstation + twin sockets','Equipment',250,'D',1.05,'general'],['tv','TV / media outlet','Equipment',120,'A',.65,'general'],['projector','Ceiling projector','AV',250,'ceiling',2.70,'dedicated'],['screen','Motorized projector screen','AV',60,'A',2.45,'dedicated'],['av','AV receiver / source outlet','AV',150,'B',.65,'general'],['speaker','Passive speaker / cable point','AV',0,'B',1.80,'speaker'],
 ['rj45','Dual RJ45 outlet','Data',0,'D',1.05,'data'],['ap','Wi-Fi access point','Data',15,'ceiling',2.80,'poe'],['camera','PoE CCTV camera','Data',12,'B',2.60,'poe'],['intercom','Video door intercom','Data',12,'C',1.40,'poe'],['hdmi','Accessible HDMI / fibre-AV conduit','AV',0,'ceiling',2.70,'avpath'],
 ['fridge','Refrigerator outlet','Kitchen',200,'A',1.20,'dedicated'],['hob','Electric hob provision','Kitchen',3000,'A',.65,'dedicated'],['oven','Oven outlet','Kitchen',2500,'A',.65,'dedicated'],['hood','Cooker hood outlet','Kitchen',150,'A',2.10,'dedicated'],['dishwasher','Dishwasher outlet','Kitchen',1500,'D',.65,'dedicated'],['purifier','Water purifier outlet','Kitchen',40,'D',1.30,'general'],['counter','Kitchen counter twin sockets','Kitchen',1000,'B',1.15,'general'],
 ['heater','Water heater + isolation','Appliances',2000,'B',2.10,'dedicated'],['washer','Washing machine outlet','Appliances',1000,'B',1.15,'dedicated'],['dryer','Dryer outlet','Appliances',2000,'B',1.15,'dedicated'],['pump','Pump supply / starter provision','Appliances',750,'B',1.20,'dedicated'],['gate','Gate motor supply','Outdoor',500,'C',.45,'dedicated'],['ev','EV empty route reservation','Outdoor',0,'C',1.20,'reserve'],['solar','Solar / battery empty route','Outdoor',0,'B',1.50,'reserve'],
 ['cold','Cold-water connection','Plumbing',0,'B',.60,'plumbing'],['hot','Hot-water connection','Plumbing',0,'B',.60,'plumbing'],['waste','Trapped waste connection','Plumbing',0,'B',.30,'plumbing'],['valve','Accessible isolation valve','Plumbing',0,'B',.60,'plumbing'],['leak','Leak sensor provision','Plumbing',2,'floor',.02,'control']
].map(([id,name,category,watts,surface,height,group])=>({id,name,category,watts,surface,height,group}));
export const byType=Object.fromEntries(library.map(t=>[t.id,t]));
export const allRooms=[...rooms.flat().map(r=>({...r,floor:r.id[0]==='g'?0:1})),...[[ 'g-court','Front court (approx.)',[-1,12.85],[10.6,5]],['g-side-left','Left side passage',[-1,0],[1,12.85]],['g-side-right','Right side passage',[8.6,0],[1,12.85]]].map(([id,name,pos,dim])=>({id,name,floor:0,dim,rect:[44+pos[0]*74,40+pos[1]*74,dim[0]*74,dim[1]*74],kind:'site'}))];
export const roomById=Object.fromEntries(allRooms.map(r=>[r.id,r]));
export function origin(r){return [(r.rect[0]-meta.origin[r.floor][0])/meta.scale,(r.rect[1]-meta.origin[r.floor][1])/meta.scale]}
let serial=Date.now();
export function makePoint(type,roomId,patch={}){const r=roomById[roomId],t=byType[type];return {id:`P${++serial}`,type,roomId,u:r.dim[0]/2,v:r.dim[1]/2,height:t.height,surface:t.surface,watts:t.watts,qty:1,inverter:['downlight','fan','night','sconce','pc','rj45','ap','camera','projector','av'].includes(type),label:t.name,...patch};}
export function clampPoint(p){const r=roomById[p.roomId];p.u=Math.max(.05,Math.min(r.dim[0]-.05,+p.u||.05));p.v=Math.max(.05,Math.min(r.dim[1]-.05,+p.v||.05));p.height=Math.max(0,Math.min(2.84,+p.height||0));if(p.surface==='A')p.v=.04;if(p.surface==='B')p.u=r.dim[0]-.04;if(p.surface==='C')p.v=r.dim[1]-.04;if(p.surface==='D')p.u=.04;if(p.surface==='ceiling')p.height=Math.max(2.5,p.height);if(p.surface==='floor')p.height=.02;return p;}
export function defaultProject(){let points=[];const typeMap={AC:'ac',RJ:'rj45',F:'fan',L:'downlight',NL:'sconce',NR:'sconce',BS:'bedstation',SW:'switch',R:'curtain',TV:'tv','2S':'socket2'};
 for(const f of [0,1])for(const p of allElectrical(f).filter(p=>p.offset)){const r=roomById[p.roomId];let type=typeMap[p.type]||'socket2';if(p.id.endsWith('-PC'))type='pc';if(p.id.endsWith('-N'))type='night';let surface=p.aff==='Ceiling'?'ceiling':p.id.match(/-(NL|NR|BL|BR)$/)?'C':p.offset[0]<.25?'D':p.offset[0]>r.dim[0]-.25?'B':p.offset[1]<.25?'A':'C';points.push(clampPoint(makePoint(type,r.id,{id:p.id,u:p.offset[0],v:p.offset[1],height:typeof p.aff==='number'?p.aff:2.84,surface,label:p.name})));}
 const add=(type,id,u,v,surface,height)=>points.push(clampPoint(makePoint(type,id,{u,v,surface,height})));
 for(const r of allRooms.filter(r=>!['bed','prayer','site'].includes(r.kind)&&!['g-living','f-living'].includes(r.id))){add(r.kind==='outdoor'?'outdoorlight':r.id==='g-dining'?'pendant':'downlight',r.id,r.dim[0]/2,r.dim[1]/2,'ceiling',2.84);if(r.kind==='wet'){add('exhaust',r.id,r.dim[0]-.3,.04,'A',2.3);add('heater',r.id,r.dim[0]-.04,.5,'B',2.1);add('cold',r.id,.04,.65,'D',.6);add('waste',r.id,.04,1.0,'D',.3);}}
 for(const [type,u,v,s,h] of [['fridge',2.4,.4,'B',1.2],['hob',1.2,.04,'A',.65],['hood',1.2,.04,'A',2.1],['oven',1.8,.04,'A',.65],['dishwasher',.04,2.2,'D',.65],['purifier',.04,2.6,'D',1.3],['counter',2.58,1.5,'B',1.15],['strip',.04,1.3,'D',1.45],['cold',.04,2.6,'D',.6],['waste',.04,2.6,'D',.3]])add(type,'g-kitchen',u,v,s,h);
 add('washer','f-laundry',1.56,1.2,'B',1.15);add('dryer','f-laundry',1.56,.8,'B',1.15);add('cold','f-laundry',.04,1.2,'D',.6);add('waste','f-laundry',.04,1.2,'D',.3);
 add('projector','f-living',1.67,2.10,'ceiling',2.70);add('screen','f-living',1.67,.04,'A',2.45);add('hdmi','f-living',1.67,2.10,'ceiling',2.70);add('av','f-living',3.30,2.1,'B',.65);add('speaker','f-living',.35,.04,'A',1.8);add('speaker','f-living',2.95,.04,'A',1.8);
 add('ap','g-dining',2.8,2.1,'ceiling',2.8);add('ap','f-living',2.7,1.2,'ceiling',2.8);add('camera','g-sitout',.3,1.8,'C',2.6);add('camera','g-work',.04,.3,'D',2.6);add('camera','g-bed-rear',3.69,.3,'B',2.6);add('camera','f-balcony',4.3,1.8,'C',2.6);
 for(const id of ['g-living','f-living']){const rj=makePoint('rj45',id,{id:id+'-media-data',u:1.65,v:.04,height:.65,surface:'A',label:'Media dual RJ45'});points.push(clampPoint(rj));}
 for(const rr of allRooms.filter(r=>r.kind==='bed'||['g-living','f-living','g-prayer'].includes(r.id))){const main=points.find(p=>p.roomId===rr.id&&p.id.endsWith('-L'));if(main){main.u=.5;main.v=.5;main.label='Ambient downlight 1';}for(const [idx,u,v] of [[2,rr.dim[0]-.5,.5],[3,.5,rr.dim[1]-.5],[4,rr.dim[0]-.5,rr.dim[1]-.5]]){if(rr.kind==='prayer'&&idx>2)continue;points.push(clampPoint(makePoint('downlight',rr.id,{id:rr.id+'-ambient-'+idx,u,v,surface:'ceiling',height:2.84,label:'Ambient downlight '+idx})));}}
 for(const [id,type,u,v,s,h] of [['g-court','camera',1,4.8,'C',1.8],['g-court','camera',9.5,4.8,'C',2],['g-side-left','camera',.5,11.8,'C',2.6],['g-side-right','camera',.5,11.8,'C',2.6],['g-court','gate',4.2,4.8,'C',.45],['g-court','intercom',.5,4.8,'C',1.4],['g-court','ev',8.5,4.8,'C',1.2],['g-court','outdoorlight',5.3,4.8,'C',1.8],['g-side-left','outdoorlight',.5,4,'D',1.8],['g-side-right','outdoorlight',.5,4,'B',1.8]])points.push(clampPoint(makePoint(type,id,{id:id+'-'+type+'-'+String(u).replace('.','_'),u,v,surface:s,height:h})));
 return {schema:1,seedVersion:3,points,db:[{x:4.45,z:5.43,height:1.5},{x:4.15,z:7.43,height:1.5}],rack:{x:4.04,z:5.14,height:1.5},waste:15,roomFinishes:{},feederCores:5};
}
export function worldPoint(p){const r=roomById[p.roomId],[x,z]=origin(r);return [x+p.u,r.floor*3+p.height,z+p.v];}
const dist=(a,b)=>Math.abs(a[0]-b[0])+Math.abs(a[1]-b[1])+Math.abs(a[2]-b[2]);
const routeTo=(p,source)=>{const r=roomById[p.roomId],end=worldPoint(p),high=r.floor*3+2.65;if(r.kind==='site')return [source,[source[0],2.65,source[2]],[4.25,2.65,source[2]],[4.25,2.65,12.85],[4.25,-.5,12.85],[4.25,-.5,end[2]],[end[0],-.5,end[2]],end];return [source,[source[0],high,source[2]],[4.25,high,source[2]],[4.25,high,end[2]],[end[0],high,end[2]],end];};
export function calculate(project){const routes=[],circuits=new Map(),bom=new Map(),phase={R:0,Y:0,B:0};let wiring=0,conduit=0,dataCable=0,dataConduit=0,spareConduit=0,switchWire=0,load=0,essential=0,unresolved=0;
 const item=(key,qty,unit,note)=>{const b=bom.get(key)||{name:key,qty:0,unit,note};b.qty+=qty;bom.set(key,b);};
 for(const p of project.points){const t=byType[p.type],r=roomById[p.roomId],f=r.floor,n=Math.max(1,p.qty);item(t.name,n,'pcs',p.label);const extraSockets=['pc','tv','av','counter'].includes(p.type);if(extraSockets)item('Twin socket outlet positions (included above)',n,'pcs','Do not add twice when purchasing packaged points.');if(['socket2','socket1','usb','bedstation','switch','dimmer','pc','tv','av','counter'].includes(p.type))item('Outlet / switch back box',n,'pcs','Depth/modules and wet/exterior suitability to specify');
  if(t.group==='plumbing'){unresolved++;continue;}if(t.group==='control'){if(p.type==='leak')unresolved++;continue;}
  const low=['data','poe','speaker','avpath'].includes(t.group),reserve=t.group==='reserve';let source=low?[project.rack.x,project.rack.height,project.rack.z]:[project.db[f].x,f*3+project.db[f].height,project.db[f].z];if(['speaker','avpath'].includes(t.group)){const av=project.points.find(q=>q.roomId===p.roomId&&q.type==='av');if(av)source=worldPoint(av);}
  let route=routeTo(p,source),length=route.slice(1).reduce((sum,v,i)=>sum+dist(route[i],v),0);routes.push({id:p.id,points:route,length,domain:low?'data':reserve?'reserve':p.inverter?'essential':'power'});
  if(low){dataConduit+=length;if(['data','poe'].includes(t.group)){const runs=t.group==='data'?2:1;dataCable+=(length+2)*runs*n;item('Data cable home runs',runs*n,'runs','Rack to outlet; dual RJ45 has two runs');}else if(t.group==='speaker')item('Speaker cable, raw route estimate',(length+2)*n,'m','Gauge/impedance/loudspeaker design pending');else item('AV conduit route',length,'m','Included in data/control conduit total; cable length depends on bends and selected medium');if(t.group==='poe'){load+=p.watts*n;essential+=p.inverter?p.watts*n:0;}continue;}
  if(reserve){spareConduit+=length;continue;}
  const key=t.group==='dedicated'?p.id:`${p.roomId}-${t.group}-${p.inverter?'E':'N'}`;const c=circuits.get(key)||{id:`C${String(circuits.size+1).padStart(2,'0')}`,key,room:r.name,floor:f,essential:p.inverter,points:[],watts:0,length:0,wireLength:0,kind:t.group};c.points.push(p.id);c.watts+=p.watts*n;c.length+=length;c.wireLength+=(length+2)*3*n;circuits.set(key,c);load+=p.watts*n;if(p.inverter)essential+=p.watts*n;conduit+=length;wiring+=(length+2)*3*n;
 }
 // Each wall switch station gets a separate provisional 2-core control route to a room lighting point.
 for(const p of project.points.filter(p=>['switch','bedstation','dimmer'].includes(p.type))){const light=project.points.find(q=>q.roomId===p.roomId&&byType[q.type].group==='lighting');if(!light){unresolved++;continue;}const a=worldPoint(p),b=worldPoint(light),high=roomById[p.roomId].floor*3+2.65,route=[a,[a[0],high,a[2]],[b[0],high,a[2]],[b[0],high,b[2]],b],len=route.slice(1).reduce((s,v,i)=>s+dist(route[i],v),0);switchWire+=(len+1)*2;conduit+=len;routes.push({id:p.id+'-control',points:route,length:len,domain:'control'});}
 let cs=[...circuits.values()].sort((a,b)=>Number(b.essential)-Number(a.essential)||b.watts-a.watts);for(const c of cs){c.phase=c.essential?'R':Object.keys(phase).sort((a,b)=>phase[a]-phase[b])[0];phase[c.phase]+=c.watts;}
 const db0=[project.db[0].x,project.db[0].height,project.db[0].z],db1=[project.db[1].x,3+project.db[1].height,project.db[1].z],feeder=dist(db0,db1)+2;
 const factor=1+project.waste/100;
 item('Final-circuit conductor allowance, all sizes combined',(wiring+switchWire)*factor,'m','3 conductors per independent endpoint run + 2 provisional control cores; includes 2 m endpoint allowance and selected waste. Cable sizes NOT assigned.');
 item('Power / control conduit allowance',conduit*factor,'m','One independent conduit per endpoint/control run. Shared-run optimization, fill, size and actual site routing unresolved.');item('Data cable allowance',dataCable*factor,'m','Pure copper category to specify; 2 m termination slack per run + waste.');item('Data / AV conduit allowance',dataConduit*factor,'m','Separate from mains; no fill/segregation design implied.');item('Empty future conduit allowance',spareConduit*factor,'m','No cable counted for empty EV/PV reserves.');item('Upper DB feeder conductor allowance',feeder*project.feederCores*factor,'m','5-core concept (3P+N+PE); conductor sizes/protection and backup feeder excluded pending design.');item('Upper DB feeder conduit allowance',feeder*factor,'m','Separate from final point routes; incoming meter and backup/source routes unmeasured.');item('Final circuit protective-device positions',cs.length,'positions','Number of circuit groups only; ratings, poles, protection type and spare ways to specify.');item('Distribution boards',2,'pcs','Editable proposed positions; physical boards/ways calculated after final circuit design.');
 return {routes,circuits:cs,bom:[...bom.values()],phase,load,essential,unresolved,raw:{wiring,switchWire,conduit,dataCable,dataConduit,spareConduit,feeder},excluded:'Meter to main DB, inverter/solar source wiring, earthing and bonding, AC refrigerant/condensate, plumbing pipe lengths, junction/pull boxes, bends, clips, glands and supports require separate measured design. No pipe lengths inferred from electrical routes.'};
}
